### ISSUE TITLE
Doesn't launch, only an empty console window appears

### ISSUE THREAD

**Issue by PureTryOut** [xoxor4d/iw3xo-radiant#21]
Hi, trying to run iw3xo-radiant for the first time but I'm having some trouble with it. When I run `bin/IW3xRadiant.exe` only an empty console window appears. I hear my CPU fan turning on, loud, and a core is being utilized for 100% but no actual application window appears. iw3xo itself runs fine however.

I am running this through Wine on Linux if it matters. After a bit of messing around I did manage to get the window to appear once but I failed to reproduce it afterwards.

**Comment by xoxor4d** [comment]
Mh I'm not a linux guy and this was never tested on wine. Should be good if iw3xo runs tho I guess?
The main difference I can think of is that radiant is saving and reading some preferences to the registery on start-up. How is that handled on wine?

Stuff to check:
- CoD4 Modtools installed?
- Does stock radiant work? 
- ^ If so, delete `imgui.ini` & `dvars.cfg` in the IW3xRadiant folder + delete the "registery" key it created `HKCU\Software\iw\IW3xRadiant` and try again

**Comment by PureTryOut** [comment]
Wine handles registry things just fine. They have to seeing it's such a key functionality in Windows.

> CoD4 Modtools installed?

Yes.

> Does stock radiant work?

Yes.

> ^ If so, delete imgui.ini & dvars.cfg in the IW3xRadiant folder + delete the "registery" key it created HKCU\Software\iw\IW3xRadiant and try again

Done, for the files. I do not seem to have a `HKCU\Software\iw\IW3XRadiant` key. What is the path from the root of the registry exactly? Just removing the files wasn't enough sadly.

**Comment by xoxor4d** [comment]
HKCU means HKEY_CURRENT_USER

Not sure what else I could suggest tbh. Would require starting radiant with a debugger attached to see where it fails

**Comment by PureTryOut** [comment]
I'm willing to do that. On Linux that'd normally be `gdb <application>`, but how do you normally debug Windows applications? I hope I don't need a full Visual Studio environment...? Sadly I see nothing logged to the console.

**Comment by PureTryOut** [comment]
So how would I start Radiant with a debugger attached? :sweat_smile:

**Comment by xoxor4d** [comment]
Sorry for taking so long to respond. The Best way would be to debug the app using Visual Studio but you might try vscode before installing a full ide

**Comment by PureTryOut** [comment]
Uh that's hard if not possible. VSCode has no idea about Wine and wouldn't know how to debug a Windows program as it  can't even execute Windows things by itself. Would it be possible to get some debug build with extra debug logging enabled or something?
