### ISSUE TITLE
[bug] Popups behind grid

### ISSUE THREAD

**Issue by Iswenzz** [xoxor4d/iw3xo-radiant#22]
Happened multiple times, not sure how to recreate the bug

![image](https://user-images.githubusercontent.com/26555415/219964426-ccc0b23c-2245-4f99-ac16-350800c43542.png)

**Comment by xoxor4d** [comment]
If you can't bring windows in-front of the grid or the camera window, then its most likely that you have toggled the original grid/camera window via the hotkey (Shift + Ctrl + V for camera or C for Grid).
I should really disable these hotkeys by default since they no longer serve a purpose.
