### ISSUE TITLE
[bug] Toolbox doesn't close when pressing N again

### ISSUE THREAD

**Issue by Iswenzz** [xoxor4d/iw3xo-radiant#23]
Layer popup works when i press L again, the toolbox doesn't close

![image](https://user-images.githubusercontent.com/26555415/219964639-cc5366e5-ec3b-400e-b3d0-547186984826.png)

**Comment by xoxor4d** [comment]
The toolbox is supposed to stay open and not to toggle with the integrated entity-properties (or any other integrated) window. You can toggle the whole toolbox by using `Q` or you can disable the integration of certain windows under the `Preferences - Gui - Property Editor & Toolbox` section

**Comment by Iswenzz** [comment]
Q is working, didn't know this key opened it, what was the reason for removing the toggle with N key ? im just used to it 🤣

**Comment by xoxor4d** [comment]
You can still toggle the property editor with `N` if its not integrated into the toolbox. If its integrated, pressing `N` will only switch to that tab within the toolbox. Same goes for the surface inspector (`S`)
