### ISSUE TITLE
[bug] Surface inspector

### ISSUE THREAD

**Issue by Iswenzz** [xoxor4d/iw3xo-radiant#25]
Manual edit with specific values seems to only work for Sample, - + buttons doesn't update the value in the inputs and the inc/dec value, the Set Specific Values checkbox is prob not needed, and the - buttons only increments for me

![image](https://user-images.githubusercontent.com/26555415/219974705-08fa055d-62ac-4266-90ce-114cb561434b.png)

**Comment by xoxor4d** [comment]
this should be resolved now 🙌
