### ISSUE TITLE
License of this project?

### ISSUE THREAD

**Issue by DanielGibson** [xoxor4d/iw3xo-radiant#26]
Hi, I'm wondering what the license of this project is.
https://github.com/xoxor4d/iw3xo-radiant/blob/develop/readme/licenses.txt mentions the MIT license, but it's unclear (to me) whether that's just about the listed libs or your own source as well.

The reason I'm asking is that I was thinking about evaluating if the iw3xo-radiant source (or parts of it) could be ported to [dhewm3](https://github.com/dhewm/dhewm3/) (Doom3 source port), which is only possible with code under a license compatible to the GPLv3.

*(Disclaimer for any dhewm3 user reading this: Even if the license turns out compatible, it doesn't mean I'll actually port this to dhewm3, and much less that I'd do it anytime soon)*

**Comment by xoxor4d** [comment]
Hey Daniel,

this project is licensed under MIT so you should be in the green. I've updated the license file accordingly.

**Comment by DanielGibson** [comment]
Awesome, thanks a lot for the clarification! :)
